baseurl = ""
# relativeURLs = true
publishDir = "docs"
title = "Sumanta's Blog"
theme = "whiteplain-loc"
languageCode = "en"
# Disqus shortname
# disqusShortname = "Shortname"
# google analytics tracking id
# googleAnalytics = "Tracking ID"

# Copyright notice. This is displayer in the footer.
copyright = "&copy; Copyright 2018 Sumanta Bose"

[params]
  # Date format
  # dateFormat = "January 2, 2006"

# This is displayer in About page.
[params.author]
  name = "Sumanta Bose"
  # Gravatar or Abatar image
  # gravatar = "Gravatar email or MD5 Hash"
  # avatar = "/path/to/avatar"

  twitter = "sumobose"
  facebook = "sumantab"
  # googleplus = "Googleplus username"
  instagram = "sumobose"
  # tumblr = "Tumblr username"
  # flickr = "Flickr username"
  # reddit = "Reddit username"
  linkedin = "sumanta-bose-1a792a36"
  # slideshare = "Slideshare username"
  github = "sumantabose"
  # gitlab = "Gitlab username"
  # bitbucket = "Bitbucket username"
  # stackoverflow = "Stackoverflow username"
  # jsfiddle = "Jsfiddle username"
  # codepen = "Codepen username"
  # deviantart = "Deviantart username"
  # behance = "Behance username"
  # dribbble = "Dribbble username"
  # wordpress = "Wordpress username"
  # medium = "Medium username"
  # foursquare = "Foursquare username"
  # xing = "Xing username"
  # quora = "Quora username"
  # youtube = "Youtube username"
  # vimeo = "Vimeo username"
  # whatsapp = "006598612535"
  # skype = "Skype username"
  # snapchat = "Snapchat username"
  # pinterest = "Pinterest username"
  # telegram = "Telegram username"
  # vine = "Vine username"
  link = "http://sumantabose.me/"
  email = "sumantabose@ntu.edu.sg"
  phone = "+65-98612535"

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

# Header Menu
[[menu.main]]
  name = "Categories"
  identifier = "categories"
  url = "/categories/"
  weight = 1
[[menu.main]]
  name = "Tags"
  identifier = "tags"
  url = "/tags/"
  weight = 2
[[menu.main]]
  name = "Archives"
  identifier = "archives"
  url = "/archives/"
  weight = 3
[[menu.main]]
  name = "About"
  identifier = "about"
  url = "/about/"
  weight = 4
[[menu.main]]
  name = "Homepage"
  url = "http://sumantabose.me/"
  weight = 5

# Footer Menu
[[menu.footer]]
  name = "About"
  weight = 1
  identifier = "about"
  url = "/about/"
